#!/bin/bash

ip_address=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

cat<<EOF > /etc/hosts
# This file is automatically generated by /usr/sbin/update-hosts.sh
127.0.0.1    localhost.localdomain    localhost
$ip_address    $HOSTNAME
EOF
